// This test-only publisher is compiled on the ephemeral runner against the
// Message Compiler header generated from the owned fixture manifest. It is
// never linked into an observer artifact.
#include <windows.h>
#include <evntprov.h>
#include <wchar.h>

#include "fixture.h"

static const GUID expected_provider = {
    0x4f0a8ead, 0x523c, 0x4f1d, {0x9d, 0x5e, 0x30, 0xd0, 0x3a, 0x30, 0xf8, 0x1b}
};

static BOOL descriptor_matches(const EVENT_DESCRIPTOR *descriptor, USHORT id,
                               UCHAR channel, UCHAR level) {
    return descriptor->Id == id && descriptor->Version == 0 &&
           descriptor->Channel == channel && descriptor->Level == level &&
           descriptor->Opcode == 0 && descriptor->Task == 0 &&
           (descriptor->Keyword & 0x1ULL) == 0x1ULL;
}

static BOOL generated_manifest_matches(void) {
    return IsEqualGUID(&HLO_FIXTURE_PROVIDER, &expected_provider) &&
           descriptor_matches(&HLO_SYSTEM_INFO, 101, 16, 4) &&
           descriptor_matches(&HLO_SYSTEM_WARN, 102, 16, 3) &&
           descriptor_matches(&HLO_SYSTEM_AFTER, 103, 16, 2) &&
           descriptor_matches(&HLO_APPLICATION_ERROR, 201, 17, 2) &&
           descriptor_matches(&HLO_APPLICATION_CRITICAL, 202, 17, 1) &&
           descriptor_matches(&HLO_APPLICATION_AFTER, 203, 17, 4);
}

// Use the registration and event-write wrappers generated by Message Compiler.
// Besides calling the public ETW APIs, these wrappers maintain MC's provider
// context and per-event enablement bits for the registered manifest provider.
#define HLO_CONCAT_INNER(left, right) left##right
#define HLO_CONCAT(left, right) HLO_CONCAT_INNER(left, right)
#define HLO_WRITE_GENERATED(event_name)                                      \
    do {                                                                     \
        while (!HLO_CONCAT(EventEnabled, event_name)()) {                    \
            if (GetTickCount64() - started >= 10000) {                       \
                return ERROR_NOT_READY;                                      \
            }                                                                \
            Sleep(25);                                                       \
        }                                                                    \
        status = HLO_CONCAT(EventWrite, event_name)(1UL);                    \
        if (status != ERROR_SUCCESS) {                                       \
            return status;                                                   \
        }                                                                    \
    } while (0)

static DWORD write_before(void) {
    ULONGLONG started = GetTickCount64();
    DWORD status;

    HLO_WRITE_GENERATED(HLO_SYSTEM_INFO);
    HLO_WRITE_GENERATED(HLO_SYSTEM_WARN);
    HLO_WRITE_GENERATED(HLO_APPLICATION_ERROR);
    HLO_WRITE_GENERATED(HLO_APPLICATION_CRITICAL);
    return ERROR_SUCCESS;
}

static DWORD write_after(void) {
    ULONGLONG started = GetTickCount64();
    DWORD status;

    HLO_WRITE_GENERATED(HLO_SYSTEM_AFTER);
    HLO_WRITE_GENERATED(HLO_APPLICATION_AFTER);
    return ERROR_SUCCESS;
}

int wmain(int argc, wchar_t **argv) {
    BOOL before;
    DWORD status;

    if (argc != 2) {
        return 2;
    }
    if (!generated_manifest_matches()) {
        return 4;
    }
    if (wcscmp(argv[1], L"before") == 0) {
        before = TRUE;
    } else if (wcscmp(argv[1], L"after") == 0) {
        before = FALSE;
    } else {
        return 2;
    }

    status = EventRegisterBraidenM_HomeLabObserver_NativeFixture();
    if (status != ERROR_SUCCESS) {
        return 1;
    }
    status = before ? write_before() : write_after();
    if (EventUnregisterBraidenM_HomeLabObserver_NativeFixture() != ERROR_SUCCESS) {
        status = ERROR_INVALID_STATE;
    }
    if (status == ERROR_NOT_READY) {
        return 3;
    }
    return status == ERROR_SUCCESS ? 0 : 1;
}
